services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  Server:
    build: ./Server
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/notesdb

  client:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "5173:80"
    environment:
      - VITE_APP_API_URL=http://server:5000

volumes:
  mongo-data:
